# Generated by Django 2.2.15 on 2020-11-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='votos',
            field=models.IntegerField(default=0, verbose_name='Votos'),
        ),
    ]
